openapi: 3.0.0
info:
    title: testEx Copy
    version: 3b128974-45f3-4048-8f83-04122485227c
    description: "description\r\n```\r\nในกรณีที่เรียกจากฝั่ง server\r\nให้เพิ่ม http request header\r\nx-service-token    2zTBruhVv5U6vMUarykEqZTWgM6GP2Jj\r\n\r\nส่วนกรณีที่เรียกจากฝั่ง client \r\nให้เพิ่ม http request header\r\nAuthorization    Bearer <access_token>\r\n```"
    termsOfService: ''
    contact: {}
    license:
        name: ''
servers:
    -
        url: 'https://{host}'
        description: ''
        variables:
            host:
                default: skill.deep.go.th
paths:
    /api/exs/store:
        get:
            servers:
                -
                    url: 'https://{host}'
                    variables:
                        host:
                            default: DefaultParameterValue
            tags:
                - ex
            parameters:
                -
                    $ref: '#/components/parameters/redirect'
                -
                    $ref: '#/components/parameters/transection'
                -
                    $ref: '#/components/parameters/exId'
            responses:
                '200':
                    description: ''
            operationId: createEx
            summary: create Ex
            description: "| | |\r\n|--|--|\r\n1 | redirect มาที่ https://`{{host}}`/api/exs/store?redirect=`{{url_redirect}}`&transection=`{{transection}}`&exId=1\r\n2 | ส่ง access_token มากับ hearder  Authorization Bearer `{{access_token}}`\r\n3 | สร้างหรือแก้ไขข้อสอบเสร็จ จะส่งข้อมูลกลับไปยัง `{{url_redirect}}`\r\n\r\n---\r\n| Header | Value |\r\n|---|---|\r\nAuthorization | Barer `USER_ACCESS_TOKEN`\r\n\r\n---\r\n\r\n### ข้อมูลที่ส่งกลับไป\r\n| | Key | Value\r\n|--|--|--|\r\n1 | exId | คือ id exam ที่ถูกสร้างหรือแก้ไข\r\n2 | name | คือ ชื่อ exam ที่ถูกสร้างหรือแก้ไข\r\n3 | transection | คือ `{{transection}}` ที่ได้ส่งมา"
    /api/exs/user:
        get:
            tags:
                - ex
            parameters:
                -
                    style: form
                    name: redirect
                    description: url ที่ส่งข้อมูลกลับ
                    schema:
                        type: string
                        example: '{{url_redirect}}'
                    in: query
                    required: true
                -
                    style: form
                    name: transection
                    description: เป็น timestamp
                    schema:
                        type: string
                        example: '{{transection}}'
                    in: query
                    required: true
                -
                    $ref: '#/components/parameters/timeLimit'
                -
                    style: form
                    name: exId
                    description: id ที่ต้องการ testing
                    schema:
                        type: number
                    in: query
                    required: true
                -
                    $ref: '#/components/parameters/passScore'
            responses:
                '200':
                    description: ''
            operationId: testingEx
            summary: testing Ex
            description: "| | |\r\n|--|--|\r\n1 | redirect มาที่ `{{url_deep}}`/api/exs/user?redirect=`{{url_redirect}}`&transection=`{{transection}}`&timeLimit=`{{secondTime}}`&exId=`1`&passScore=`50`\r\n2 | ส่ง access_token มากับ hearder  Authorization Bearer `{{access_token}}`\r\n3 | ทำข้อสอบเสร็จ จะส่งข้อมูลกลับไปยัง `{{url_redirect}}`\r\n\r\n### ข้อมูลที่ต้องส่งมา (request)\r\n| | Key | Value\r\n|--|--|--|\r\n1 | redirect | ลิ่งที่จะส่งกลับ\r\n2 | transection | \r\n3 | timeLimit | ระบุจำนวนเวลาในการทำแบบฝึกหัด( วินาที )\r\n4 | exId | ระบุ exam ที่ต้องการ\r\n5 | passScore | เกณร์คะแนนผ่านแบบฝึกหัด ( เปอร์เช็น )\r\n\r\n---\r\n\r\n| Header | Value |\r\n|---|---|\r\nAuthorization | Barer `USER_ACCESS_TOKEN`\r\n\r\n---\r\n\r\n### ข้อมูลที่ส่งกลับไป (response)\r\n| | Key | Value\r\n|--|--|--|\r\n1 | exId | คือ id exam testing\r\n2 | score | คือ คะแนนที่ทำได้\r\n3 | duration | คือ เวลาที่ใช้ไป\r\n4 | transection | คือ `{{transection}}` ที่ได้ส่งมา\r\n5 | code | คือ keyid ของ log\r\n6 | isPass | complete คือสอบผ่าน ส่วน not-complete คือสอบไม่ผ่าน\r\n7 | rawScore | คือ คะแนนดิบ\r\n8 | maxScore | คือ คะแนนเต็ม\r\n9 | timetable_id | "
    /api/exs/log:
        get:
            servers:
                -
                    url: 'https://{host}'
                    variables:
                        host:
                            default: DefaultParameterValue
            tags:
                - ex
            parameters:
                -
                    $ref: '#/components/parameters/code'
                -
                    style: form
                    name: transection
                    schema:
                        type: string
                        example: '{{transection}}'
                    in: query
                    required: true
            responses:
                '200':
                    description: ''
            operationId: getLogดูแบบฝึกหัดย้อยหลัง
            summary: get Log ดูแบบฝึกหัดย้อยหลัง
    '/api/exs/report/{idEx}':
        get:
            servers:
                -
                    url: 'https://{host}'
                    variables:
                        host:
                            default: DefaultParameterValue
            tags:
                - ex
            parameters:
                -
                    $ref: '#/components/parameters/idEx'
            responses:
                '200':
                    description: ''
            operationId: getReport
            summary: get Report
    /api/content/excel:
        post:
            requestBody:
                description: "| key | type |\r\n|--|--|\r\nfile_upload | file\r\n\r\nดาวน์โหลด ไฟล์รูปแบบ\r\nhttps://skill.deep.go.th/api/content/excel-format\r\n\r\nstatus 200\r\n```json\r\n{\r\n    \"code\": 200,\r\n    \"status\": \"success\",\r\n    \"list\": [\r\n        {\r\n            \"exId\": 221,\r\n            \"name\": \"AMSF\"\r\n        }\r\n    ]\r\n}\r\n```"
                content:
                    multipart/form-data:
                        schema:
                            required:
                                - file
                            type: object
                            properties:
                                file:
                                    format: binary
                                    type: string
                        example:
                            -
                                key: file_upload
                                type: file
                                src: '/F:/สำเนาของ ข้อสอบ รวม.xlsx'
                required: true
            servers:
                -
                    url: 'https://{host}'
                    variables:
                        host:
                            default: DefaultParameterValue
            tags:
                - ex
            responses:
                '200':
                    description: ''
            operationId: importexcel
            summary: import excel
            description: "| key | type |\r\n|--|--|\r\nfile_upload | file\r\n\r\nดาวน์โหลด ไฟล์รูปแบบ\r\nhttps://skill.deep.go.th/api/content/excel-format\r\n\r\nstatus 200\r\n```json\r\n{\r\n    \"code\": 200,\r\n    \"status\": \"success\",\r\n    \"list\": [\r\n        {\r\n            \"exId\": 221,\r\n            \"name\": \"AMSF\"\r\n        }\r\n    ]\r\n}\r\n```"
    /api/account:
        post:
            requestBody:
                description: "\r\nหลังจาก มีการ register เสร็จ\r\nส่งข้อมูล account เพื่อบันทึกข้อมูล\r\n\r\n---\r\nresponse\r\n\r\n```json\r\n{\r\n    \"code\": 200,\r\n    \"status\": \"success\"\r\n}\r\n```"
                content:
                    text/plain:
                        schema:
                            type: string
                            example:
                                role: TEACHER
                                google_id: '106424754561439431953'
                                email: school_teacher@moe.go.th
                                first_name_th: ผู้ดูแล
                                last_name_th: ระบบโรงเรียน
                                first_name_en: School
                                last_name_en: Admin
                                birth_date: '1990-01-01'
                                citizen_id: '5383645653684'
                                tel: '+66862336011'
                        example: "{\r\n    \"role\": \"TEACHER\",\r\n    \"google_id\": \"106424754561439431953\",\r\n    \"email\": \"school_teacher@moe.go.th\",\r\n    \"prefix_name_th\": null,\r\n    \"first_name_th\": \"ผู้ดูแล\",\r\n    \"last_name_th\": \"ระบบโรงเรียน\",\r\n    \"first_name_en\": \"School\",\r\n    \"last_name_en\": \"Admin\",\r\n    \"birth_date\": \"1990-01-01\",\r\n    \"citizen_id\": \"5383645653684\",\r\n    \"tel\": \"+66862336011\",\r\n    \"line_id\": null,\r\n    \"avatar_path\": null,\r\n    \"avatar_url\": null\r\n}"
                required: true
            tags:
                - account
            responses:
                '200':
                    description: ''
            operationId: register
            summary: register
            description: "\r\nหลังจาก มีการ register เสร็จ\r\nส่งข้อมูล account เพื่อบันทึกข้อมูล\r\n\r\n---\r\nresponse\r\n\r\n```json\r\n{\r\n    \"code\": 200,\r\n    \"status\": \"success\"\r\n}\r\n```"
    /api/notifications/unread-count:
        summary: /notifications/unread-count
        get:
            tags:
                - notification
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/noti_total'
            summary: /notifications/unread-count
    /api/notifications/read:
        patch:
            tags:
                - notification
            parameters:
                -
                    name: notiId
                    description: ''
                    schema:
                        type: string
                    in: query
                    required: true
            summary: /notifications/read
    '/api/notifications/:id':
        put:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/put_notification'
                required: true
            tags:
                - notification
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/notification'
            summary: '/notifications/:id'
    /api/subjects/user:
        get:
            tags:
                - subject
            parameters:
                -
                    $ref: '#/components/parameters/citizen_id'
                -
                    $ref: '#/components/parameters/filter'
                -
                    style: form
                    name: limit
                    description: กำหนดจำนวนข้อมูลต่อ หน้าลิสข้อมูล
                    schema:
                        type: number
                    in: query
                    required: true
                -
                    $ref: '#/components/parameters/page'
                -
                    style: form
                    name: where
                    description: ค้นหาด้วยคำสั่ง where
                    schema:
                        type: string
                        example: '{"subject.subjectId":{"<>":430}}'
                    in: query
                    required: true
                -
                    style: form
                    name: order_by
                    description: กำหนดการเรียงข้อมูล
                    schema:
                        type: string
                        example: 'createdBy,-detail.userSubjectId'
                    in: query
                    required: true
            responses:
                '200':
                    description: "```json\r\n    [\r\n        {\r\n            \"subjectId\": 500,\r\n            \"name\": \"การจดโน๊ดอย่างไรให้น่าประทับใจและดูโปร\",\r\n            \"description\": \"การอบรมทักษะพื้นฐานการใช้ iPadOS ในหัวข้อ \\\"จดโน๊ตอย่างไรให้น่าประทับใจและดูโปร\\\" โดย อ.ปัญชสา เชาวน์ชูเวชช (APLP)\",\r\n            \"userIdCreator\": \"\",\r\n            \"orgcodeCreator\": \"\",\r\n            \"isLearningOrder\": \"Y\",\r\n            \"cover\": \"\",\r\n            \"owner_name\": \"Apple Professional Learning Provider\",\r\n            \"subjectCategoryId\": \"\",\r\n            \"organizationCode\": \"\",\r\n            \"createdBy\": 101003,\r\n            \"countUnit\": \"\",\r\n            \"category\": {},\r\n            \"detail\": {\r\n                \"userSubjectId\": 13565,\r\n                \"subjectId\": 500,\r\n                \"userId\": 101003,\r\n                \"status\": \"learnt\",\r\n                \"isFinished\": \"Y\"\r\n            }\r\n        },...\r\n    ]\r\n```"
            operationId: user
            summary: user
            description: "description\r\n```\r\napi ข้อมูลการเรียนรายบุคล\r\n```\r\nparams\r\n\r\n| key | required | description | example\r\n--|--|--|--\r\ncitizen_id | true | เลขบัตรประจำตัว | 2151321154118\r\nfilter | false | ใช้ค้นหา | {\"name\":\"POD\"}\r\nlimit | false | กำหนดจำนวนข้อมูลต่อ หน้าลิสข้อมูล | 10\r\npage | false | เลขหน้าลิสข้อมูล | 1\r\norder_by | false | กำหนดการเรียงข้อมูล | createdBy,-detail.userSubjectId\r\n\r\n"
    /api/subjects/list:
        get:
            tags:
                - subject
            parameters:
                -
                    $ref: '#/components/parameters/filter'
                -
                    style: form
                    name: limit
                    description: กำหนดจำนวนข้อมูลต่อ หน้าลิสข้อมูล
                    schema:
                        type: number
                    in: query
                    required: true
                -
                    $ref: '#/components/parameters/page'
                -
                    style: form
                    name: where
                    description: ค้นหาด้วยคำสั่ง where
                    schema:
                        type: string
                        example: '{"subject.subjectId":{"<>":430}}'
                    in: query
                    required: true
                -
                    style: form
                    name: order_by
                    description: กำหนดการเรียงข้อมูล
                    schema:
                        type: string
                        example: 'createdBy,-detail.userSubjectId'
                    in: query
                    required: true
            responses:
                '200':
                    description: "```json\r\n    [\r\n        {\r\n            \"subjectId\": 500,\r\n            \"name\": \"การจดโน๊ดอย่างไรให้น่าประทับใจและดูโปร\",\r\n            \"description\": \"การอบรมทักษะพื้นฐานการใช้ iPadOS ในหัวข้อ \\\"จดโน๊ตอย่างไรให้น่าประทับใจและดูโปร\\\" โดย อ.ปัญชสา เชาวน์ชูเวชช (APLP)\",\r\n            \"userIdCreator\": \"\",\r\n            \"orgcodeCreator\": \"\",\r\n            \"isLearningOrder\": \"Y\",\r\n            \"cover\": \"\",\r\n            \"owner_name\": \"Apple Professional Learning Provider\",\r\n            \"subjectCategoryId\": \"\",\r\n            \"organizationCode\": \"\",\r\n            \"createdBy\": 101003,\r\n            \"countUnit\": \"\",\r\n            \"category\": {}\r\n        },...\r\n    ]\r\n```"
            operationId: list
            summary: list
            description: "description\r\n```\r\napi ข้อมูลวิชา\r\n```\r\nparams\r\n\r\n| key | required | description | example\r\n--|--|--|--\r\nfilter | false | ใช้ค้นหา | {\"name\":\"POD\"}\r\nlimit | false | กำหนดจำนวนข้อมูลต่อ หน้าลิสข้อมูล | 10\r\npage | false | เลขหน้าลิสข้อมูล | 1\r\norder_by | false | กำหนดการเรียงข้อมูล | createdBy,-detail.userSubjectId\r\n"
    /api/notifications:
        summary: /notifications
        get:
            tags:
                - notification
            parameters:
                -
                    name: search
                    description: ''
                    schema: {}
                    in: query
                -
                    name: limit
                    description: ''
                    schema: {}
                    in: query
                -
                    examples:
                        'message,userId':
                            value: 'message,userId'
                    name: search_fields
                    description: ''
                    schema: {}
                    in: query
                -
                    examples:
                        sort new to old:
                            value: '-updatedAt'
                    name: order_by
                    description: ''
                    schema: {}
                    in: query
                -
                    name: before
                    description: notiId
                    schema:
                        type: string
                    in: query
                    required: false
                -
                    name: where
                    description: ''
                    schema: {}
                    in: query
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/notification'
                            examples:
                                notifications:
                                    value:
                                        -
                                            notiId: 4698
                                            message: asdfadsf
                                            menu: ''
                                            userId: 101156
                                            refTable: ''
                                            refId: ''
                                            isRead: 1
                                            refURL: ''
                                            createdAt: '2020-10-02T03:38:47.000Z'
                                            updatedAt: '2020-10-02T04:13:27.000Z'
                                            subject: {}
                                        -
                                            notiId: 4637
                                            message: ในบทเรียนเพิ่มเติม
                                            menu: subject
                                            userId: 224
                                            refTable: ''
                                            refId: 553
                                            isRead: 0
                                            refURL: ''
                                            createdAt: '2020-08-27T08:08:04.000Z'
                                            updatedAt: '2020-08-27T08:08:04.000Z'
                                            subject:
                                                subjectId: 553
                                                name: เครื่องจักรกลเกษตรในระบบสมาร์ทฟาร์ม (AMSF)
                    description: ''
            summary: /notifications
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/post_notification'
                required: true
            tags:
                - notification
            summary: /notifications
        delete:
            tags:
                - notification
            parameters:
                -
                    name: notiId
                    description: ''
                    schema: {}
                    in: query
                    required: true
            responses:
                '200':
                    content:
                        Text:
                            examples:
                                ok:
                                    value: ok
            summary: /notifications
    /api/subjects/user-list:
        get:
            tags:
                - subject
            parameters:
                -
                    $ref: '#/components/parameters/citizen_id'
                -
                    $ref: '#/components/parameters/filter'
                -
                    style: form
                    name: limit
                    description: กำหนดจำนวนข้อมูลต่อ หน้าลิสข้อมูล
                    schema:
                        type: number
                    in: query
                    required: true
                -
                    $ref: '#/components/parameters/page'
                -
                    style: form
                    name: where
                    description: ค้นหาด้วยคำสั่ง where
                    schema:
                        type: string
                        example: '{"subject.detail.subjectId":{"<>":430}}'
                    in: query
                    required: true
                -
                    style: form
                    name: order_by
                    description: กำหนดการเรียงข้อมูล
                    schema:
                        type: string
                        example: name
                    in: query
                    required: true
            responses:
                '200':
                    description: |-
                        ```json
                        [
                            {
                                "userId": 101010,
                                "name": "ยงศักดิ์",
                                "lastname": "สุพรรณ",
                                "middlename": "",
                                "prefix": "นาย",
                                "email": "example@obec.moe.go.th",
                                "subject": [
                                    {
                                        "userSubjectId": 8759,
                                        "subjectId": 311,
                                        "userId": 101010,
                                        "status": "learning",
                                        "isFinished": "Y",
                                        "detail": {
                                            "subjectId": 311,
                                            "name": "หลักสูตรการยกระดับพัฒนาทักษะความเข้าใจด้านการใช้เทคโนโลยีดิจิทัล",
                                            "description": "หลักสูตรการยกระดับพัฒนาทักษะความเข้าใจด้านการใช้เทคโนโลยีดิจิทัล สำหรับข้าราชครูและบุคลากรทางการศึกษา \nด้วยประกาศนียบัตรมาตรฐานสากล IC3 Digital Literacy Certification",
                                            "userIdCreator": "",
                                            "orgcodeCreator": "",
                                            "isLearningOrder": "Y",
                                            "cover": "",
                                            "owner_name": "บริษัท เออาร์ไอที จำกัด",
                                            "subjectCategoryId": "",
                                            "organizationCode": "",
                                            "createdBy": 1,
                                            "countUnit": "",
                                            "category": ""
                                        }
                                    }
                                ]
                            },...
                        ]
                        ```
            deprecated: false
            operationId: user-list
            summary: user-list
            produces:
                - application/json
components:
    schemas:
        '200':
            type: array
            items:
                type: object
                properties:
                    notiId:
                        description: ''
                        default: 4698
                        type: integer
                    message:
                        description: ''
                        default: asdfadsf
                        type: string
                    menu: {}
                    userId:
                        description: ''
                        default: 101156
                        type: integer
                    refTable: {}
                    refId: {}
                    isRead:
                        description: ''
                        default: 1
                        type: integer
                    refURL: {}
                    createdAt:
                        description: ''
                        default: '2020-10-02T03:38:47.000Z'
                        type: string
                    updatedAt:
                        description: ''
                        default: '2020-10-02T04:13:27.000Z'
                        type: string
                    subject:
                        type: object
        get_notification:
            title: Root Type for notification
            description: ''
            required:
                - message
                - userId
            type: object
            properties:
                notiId:
                    type: string
                message:
                    type: string
                menu:
                    type: string
                userId:
                    type: string
                refTable:
                    type: string
                refId:
                    type: string
                isRead:
                    type: number
                refURL:
                    type: string
            example:
                notiId: ''
                message: ''
                menu: ''
                userId: ''
                refTable: ''
                refId: ''
                isRead: ''
                refURL: ''
                createdAt: ''
                updatedAt: ''
        notiId:
            description: ''
            type: object
        notification:
            title: Root Type for notification
            description: ''
            required:
                - message
                - userId
                - notiId
            type: object
            properties:
                notiId:
                    type: string
                message:
                    type: string
                menu:
                    type: string
                userId:
                    type: string
                refTable:
                    type: string
                refId:
                    type: string
                isRead:
                    type: number
                refURL:
                    type: string
                createdAt:
                    format: date-time
                    description: ''
                    type: string
                updatedAt:
                    format: date-time
                    description: ''
                    type: string
            example:
                notiId: 4637
                message: ในบทเรียนเพิ่มเติม
                menu: subject
                userId: 224
                refTable: ''
                refId: 553
                isRead: 0
                refURL: ''
                createdAt: '2020-08-27T08:08:04.000Z'
                updatedAt: '2020-08-27T08:08:04.000Z'
                subject:
                    subjectId: 553
                    name: เครื่องจักรกลเกษตรในระบบสมาร์ทฟาร์ม (AMSF)
        noti_total:
            title: Root Type for noti_total
            description: ''
            type: object
            properties:
                total:
                    format: int32
                    type: integer
            example:
                total: 5
        post_notification:
            title: Root Type for notification
            description: ''
            required:
                - message
                - userId
                - notiId
            type: object
            properties:
                notiId:
                    type: string
                message:
                    type: string
                menu:
                    type: string
                userId:
                    type: string
                refTable:
                    type: string
                refId:
                    type: string
                isRead:
                    type: number
                refURL:
                    type: string
            example:
                notiId: 4637
                message: ในบทเรียนเพิ่มเติม
                menu: subject
                userId: 224
                refTable: ''
                refId: 553
                isRead: 0
                refURL: ''
                createdAt: '2020-08-27T08:08:04.000Z'
                updatedAt: '2020-08-27T08:08:04.000Z'
                subject:
                    subjectId: 553
                    name: เครื่องจักรกลเกษตรในระบบสมาร์ทฟาร์ม (AMSF)
        put_notification:
            title: Root Type for notification
            description: ''
            required: []
            type: object
            properties:
                message:
                    type: string
                menu:
                    type: string
                userId:
                    type: string
                refTable:
                    type: string
                refId:
                    type: string
                isRead:
                    type: number
                refURL:
                    type: string
            example:
                notiId: 4637
                message: ในบทเรียนเพิ่มเติม
                menu: subject
                userId: 224
                refTable: ''
                refId: 553
                isRead: 0
                refURL: ''
                createdAt: '2020-08-27T08:08:04.000Z'
                updatedAt: '2020-08-27T08:08:04.000Z'
                subject:
                    subjectId: 553
                    name: เครื่องจักรกลเกษตรในระบบสมาร์ทฟาร์ม (AMSF)
    parameters:
        redirect:
            style: form
            name: redirect
            description: url ที่ส่งข้อมูลกลับ
            schema:
                type: string
                example: '{{url_redirect}}'
            in: query
            required: true
        transection:
            style: form
            name: transection
            description: เป็น timestamp
            schema:
                type: string
                example: '{{transection}}'
            in: query
            required: true
        exId:
            style: form
            name: exId
            description: ใส่เพื่อแก้ไข
            schema:
                type: number
            in: query
            required: true
        timeLimit:
            style: form
            name: timeLimit
            description: ตั้งเวลาในการทำข้อสอบ (วินาที)
            schema:
                type: string
                example: '{{secondTime}}'
            in: query
            required: true
        passScore:
            style: form
            name: passScore
            description: เกณฑ์คะแนนที่ผ่าน 1-100 percen
            schema:
                type: number
            in: query
            required: true
        code:
            style: form
            name: code
            schema:
                type: string
                example: '{{code}}'
            in: query
            required: true
        idEx:
            style: simple
            name: idEx
            schema:
                type: string
                example: idEx
            in: path
            required: true
        search:
            style: form
            name: search
            schema:
                type: string
                example: schema type not provided
            in: query
            required: true
        limit:
            style: form
            name: limit
            schema:
                type: string
                example: schema type not provided
            in: query
            required: true
        search_fields:
            style: form
            name: search_fields
            schema:
                type: string
                example: schema type not provided
            in: query
            required: true
        order_by:
            style: form
            name: order_by
            schema:
                type: string
                example: schema type not provided
            in: query
            required: true
        where:
            style: form
            name: where
            schema:
                type: string
                example: schema type not provided
            in: query
            required: true
        Content-Type:
            style: simple
            name: Content-Type
            schema:
                type: string
                example: application/json
            in: header
            required: true
        notiId:
            style: form
            name: notiId
            description: '(Required) '
            schema:
                type: string
                example: schema type not provided
            in: query
            required: true
        citizen_id:
            style: form
            name: citizen_id
            description: เลขบัตรประจำตัว
            schema:
                type: number
            in: query
            required: true
        filter:
            style: form
            name: filter
            description: ใช้ค้นหา
            schema:
                type: string
                example: '{"subject.name":"POD"}'
            in: query
            required: true
        page:
            style: form
            name: page
            description: เลขหน้าลิสข้อมูล
            schema:
                type: number
            in: query
            required: true
    securitySchemes:
        bearer:
            scheme: bearer
            type: http
        noauth:
            scheme: noauth
            type: http
security:
    -
        bearer: []
    -
        bearer: []
    -
        noauth: []
    -
        bearer: []
    -
        bearer: []
    -
        bearer: []
externalDocs:
    description: ''
    url: ''
swagger: '2.0'
warnings: []
